Repository team-apm/apm, pull requests merged in 2021-10, with the labels that each got.

#154 Support dependencies
  src/core/core.js
  src/lib/parseXML.js
  src/package/package.js
  src/package/packageUtil.js
Labels: Feedback: enhancement, Type: new feature

#158 style(index.html): improve the settings page
  src/index.html
Labels: Feedback: enhancement, Type: design

#156 docs: update the manual
  docs/images/exedit.drawio.svg
  docs/images/io_filter.drawio.svg
  docs/images/screen1.png
  docs/images/screen2.png
  docs/index.md
Labels: Type: documentation, Feedback: enhancement

#157 docs: update readme
  README.en.md
  README.md
  docs/index.md
Labels: Type: documentation, Feedback: enhancement

#160 Create SECURITY.md
  SECURITY.md
  forge.config.js
Labels: Type: documentation, Feedback: enhancement

#161 docs(readme): update English readme
  README.en.md
Labels: Type: documentation, Feedback: enhancement

#162 Add files to run Jekyll on local
  docs/.gitignore
  docs/Gemfile
  docs/Gemfile.lock
  docs/_config.yml
  docs/_includes/head-custom.html
  docs/favicon.ico
  docs/images/apm1024.png
Labels: Type: documentation, Feedback: enhancement

#163 feat: use twemoji
  package.json
  src/about.html
  src/index.css
  src/index.html
  src/package/package.js
  src/package_maker.html
  src/splash.html
  yarn.lock
Labels: Feedback: enhancement, Type: design, Type: improvement

#164 refactor: replace throw with log.error & return
  src/core/core.js
  src/package/package.js
Labels: Feedback: enhancement, Type: refactoring

#165 docs(README): add links to the latest release page
  README.en.md
  README.md
Labels: Type: documentation, Feedback: enhancement

#196 feat: default installation path
  src/core/core.js
  src/main.js
  src/preload.js
Labels: Feedback: enhancement, Type: new feature
