Repository team-apm/apm, pull requests merged in 2021-09, with the labels that each got.

#78 refactor(parseXML): change to use the library to parse XML
  src/core/core.js
  src/plugin/plugin.js
  src/script/script.js
Labels: Feedback: enhancement, Type: refactoring

#82 refactor(buttonTransition): change to be able to display all types of buttons
  src/core/core.js
  src/lib/buttonTransition.js
  src/plugin/plugin.js
  src/script/script.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: refactoring

#83 fix: change to be able to cancel the installation
  src/main.js
  src/plugin/plugin.js
  src/script/script.js
Labels: Problem: bug

#71 feat: change to manage versions by JSON file in installation directory
  src/lib/apmJson.js
Labels: Feedback: enhancement, Type: new feature

#84 fix: fix an error when destroying the browser window
  src/main.js
Labels: Problem: bug

#85 refactor(script.js): fix typos
  src/script/script.js
Labels: Feedback: enhancement

#87 fix(setting): fixed dataURL initialization process
  src/setting/setting.js
Labels: Problem: bug

#88 fix: display the certificate confirmation dialog
  src/main.js
Labels: Problem: bug

#86 feat: change to manage versions by JSON file in installation directory
  src/core/core.js
  src/lib/apmJson.js
  src/plugin/plugin.js
  src/preload.js
  src/script/script.js
Labels: Feedback: enhancement, Type: improvement, Type: new feature

#89 feat(unzip): support for lzh files
  forge.config.js
  package.json
  src/lib/unzip.js
  src/main.js
  yarn.lock
Labels: Feedback: enhancement, Type: new feature

#91 fix: add missing await
  src/plugin/plugin.js
  src/script/script.js
Labels: Problem: bug

#92 feat: integrating plugins and scripts
  CONTRIBUTING.ja.md
  CONTRIBUTING.md
  src/core/core.js
  src/index.css
  src/index.html
  src/lib/apmJson.js
  src/lib/parseXML.js
  src/package/package.js
  src/preload.js
  src/script/script.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: improvement, Type: new feature, Type: refactoring

#94 fix(apmJson): write json synchronously
  src/lib/apmJson.js
Labels: Feedback: enhancement, Type: refactoring

#95 feat(parseXML): automatically generate type
  src/lib/parseXML.js
Labels: Feedback: enhancement, Type: improvement, Type: new feature, Type: refactoring

#100 feat: save window position & size and restore it on starting
  package.json
  src/main.js
  yarn.lock
Labels: Feedback: enhancement, Type: new feature

#98 docs(App Name): change the name of the app
  CONTRIBUTING.ja.md
  CONTRIBUTING.md
  README.ja.md
  README.md
  package.json
  src/about.html
  src/index.html
  src/splash.html
Labels: Feedback: enhancement, Type: improvement

#99 feat: change to use the path of the file specified in the archive in the data file
  src/lib/parseXML.js
  src/package/package.js
Labels: Feedback: enhancement, Type: improvement, Type: new feature

#101 feat: add descriptions to the UI
  src/core/core.js
  src/index.html
Labels: Feedback: enhancement, Type: design

#102 fix: fix a bug in which errors were not displayed while processing was in progress
  src/core/core.js
  src/package/package.js
  src/preload.js
Labels: Problem: bug

#109 chore: add my name to the contributions
  src/about.html
Labels: Type: documentation, Feedback: enhancement

#106 feat: add a tool for generating packages
  package.json
  src/main.js
  src/package_maker.html
  src/package_maker_preload.js
  yarn.lock
Labels: Feedback: enhancement, Type: new feature

#114 fix: change to freeze the selected package while installing or uninstalling
  src/package/package.js
Labels: Problem: bug

#115 refactor: change the default data repository
  src/setting/setting.js
Labels: Feedback: enhancement, Type: improvement

#108 feat: add a feature to display update date and time
  src/core/core.js
  src/index.html
  src/lib/mod.js
  src/lib/parseXML.js
  src/package/package.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: new feature

#116 feat(package maker): support for installers
  src/package_maker.html
  src/package_maker_preload.js
Labels: Feedback: enhancement, Type: improvement, Type: new feature

#119 refactor: change button transition of checking the latest core data
  src/core/core.js
Labels: Feedback: enhancement, Type: refactoring

#120 docs(readme): switch the default readme to Japanese
  README.en.md
  README.ja.md
  README.md
Labels: Type: documentation, Feedback: enhancement

#121 feat: add a menu to send a feedback
  src/main.js
Labels: Feedback: enhancement, Type: new feature

#123 fix: fix for sorting and filtering
  src/package/package.js
Labels: Problem: bug

#128 Refactor some code
  src/core/core.js
  src/main.js
  src/preload.js
Labels: Feedback: enhancement, Type: refactoring

#124 feat: use understandable name
  src/lib/apmJson.js
  src/package/package.js
Labels: Feedback: enhancement, Type: improvement, Type: refactoring

#127 Add a icon
  README.en.md
  README.md
  forge.config.js
  icon/LICENSE
  icon/apm.icns
  icon/apm.ico
  icon/apm1024.png
  icon/apm128.png
  icon/apm256.png
  icon/apm32.png
  icon/apm64.png
  icon/apm96.png
  src/about.html
  src/main.js
Labels: Feedback: enhancement, Type: design, Type: new feature

#125 feat: load repository data at first startup
  src/core/core.js
  src/preload.js
Labels: Feedback: enhancement, Type: new feature

#129 feat: insert the default repository when nothing is entered in the input
  src/index.html
  src/preload.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: new feature

#130 refactor: replace the unnecessary innerHTML with innerText for the security
  src/core/core.js
  src/lib/buttonTransition.js
  src/package/package.js
Labels: Feedback: enhancement, Type: refactoring

#126 docs(readme): update the readme
  README.en.md
  README.md
Labels: Type: documentation, Feedback: enhancement

#133 docs(docs): initial commit
  docs/index.md
Labels: Type: documentation, Feedback: enhancement

#132 style: change tab width from 4 to 2
  .editorconfig
  src/about.html
  src/index.html
  src/package_maker.html
Labels: Feedback: enhancement, Type: improvement

#134 docs(docs): fix the logo
  docs/images/apm32.png
  docs/index.md
  forge.config.js
Labels: Type: documentation, Feedback: enhancement

#135 fix: dataURL is not loaded on first launch
  src/setting/setting.js
Labels: Problem: bug

#136 docs(about): add about the license to the about page
  src/about.html
Labels: Type: documentation, Feedback: enhancement

#139 feat: add a button to open the download folder
  src/index.html
  src/lib/unzip.js
  src/main.js
  src/package/package.js
  src/preload.js
Labels: Feedback: enhancement, Type: new feature

#140 feat: add filtering of packages
  src/index.css
  src/index.html
  src/package/package.js
  src/preload.js
Labels: Feedback: enhancement, Type: new feature

#142 feat: install scripts without a database
  src/core/core.js
  src/index.html
  src/lib/mod.js
  src/lib/parseXML.js
  src/package/package.js
  src/preload.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: new feature

#144 build(deps): update some packages
  yarn.lock
Labels: Feedback: enhancement

#146 style(package maker): correct title
  src/package_maker.html
Labels: Feedback: enhancement, Type: improvement

#145 fix: reduce buttons
  src/index.html
  src/preload.js
Labels: Feedback: enhancement, Type: design, Type: improvement

#147 style(index.html): improve the main page
  src/index.html
Labels: Feedback: enhancement, Type: design

#148 perf: change to show some windows when ready-to-show is emitted
  src/main.js
Labels: Feedback: enhancement, Type: improvement

#149 Refactor icons and modules
  src/core/core.js
  src/lib/apmJson.js
  src/lib/buttonTransition.js
  src/lib/mod.js
  src/lib/parseXML.js
  src/lib/unzip.js
  src/main.js
  src/package/package.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: refactoring

#152 feat(log): add the feature to log uncaught exceptions and exit
  src/about_preload.js
  src/main.js
  src/package_maker_preload.js
  src/preload.js
Labels: Feedback: enhancement, Type: new feature

#153 Refactoring package.js
  src/package/package.js
  src/package/packageUtil.js
Labels: Feedback: enhancement, Type: refactoring
