Repository team-apm/apm, pull requests merged in 2021-08, with the labels that each got.

#51 fix(plugin.js): fix handling of folders containing spaces
  src/plugin/plugin.js
Labels: Problem: bug, Feedback: enhancement, Type: improvement

#49 fix(main.js): fix for splash screen clearing
  src/main.js
Labels: Problem: bug, Feedback: enhancement, Type: improvement

#55 fix(plugin.js&script.js): treat a single file as an array
  src/plugin/plugin.js
  src/script/script.js
Labels: Problem: bug, Type: improvement

#58 feat: add the feature to adjust the zoom of the display
  src/index.html
  src/main.js
  src/preload.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: new feature

#53 feat(userData&Store): separate data for production and development
  package.json
  src/main.js
  yarn.lock
Labels: Feedback: enhancement, Type: new feature

#54 feat: enables DevTools in the development environment
  package.json
  src/main.js
  yarn.lock
Labels: Feedback: enhancement, Type: improvement

#64 feat: sortable and filterable tables
  package.json
  src/index.css
  src/index.html
  src/plugin/plugin.js
  src/script/script.js
  yarn.lock
Labels: Feedback: enhancement, Type: new feature

#66 feat: bundle a file that notices the license in the package
  .gitignore
  forge.config.js
  package.json
  src/about.css
  src/about.html
Labels: Feedback: enhancement, Priority: high, Type: new feature

#67 feat: add contributors' credits
  CONTRIBUTING.ja.md
  CONTRIBUTING.md
  src/about.html
  src/main.js
Labels: Feedback: enhancement, Type: new feature

#69 feat: improve appearance of the table
  src/index.css
  src/index.html
  src/plugin/plugin.js
  src/script/script.js
Labels: Feedback: enhancement, Type: design, Type: improvement

#68 Feat(plugin&script): work with manually added plugins
  src/index.html
  src/plugin/plugin.js
  src/script/script.js
Labels: Feedback: enhancement, Type: new feature

#74 fix: fix scrolling the detail panel for a script
  src/index.html
Labels: Problem: bug, Type: design

#73 refactor: add a library to transition a button and change to use it
  src/core/core.js
  src/lib/buttonTransition.js
  src/plugin/plugin.js
  src/script/script.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: refactoring

#75 fix(plugin&script): cannot display the list of plugins
  src/plugin/plugin.js
  src/script/script.js
Labels: Problem: bug

#77 refactor: add padding to the left and right of the tables
  src/index.css
Labels: Feedback: enhancement, Type: design

#72 refactor(parseXML): add a library to parse XML
  src/lib/parseXML.js
Labels: Feedback: enhancement, Type: improvement, Type: refactoring
