Repository team-apm/apm, pull requests merged in 2021-11, with the labels that each got.

#198 feat: supports dark themes
  package.json
  src/index.html
  src/main.css
  src/package_maker.html
  yarn.lock
Labels: Feedback: enhancement, Type: design, Type: new feature

#200 refactor: improve stability of main.js
  src/main.js
Labels: Feedback: enhancement, Type: refactoring

#201 fix: make the install buttons clickable
  src/core/core.js
Labels: Feedback: enhancement, Type: design

#202 build(deps): upgrade some packages
  package.json
  yarn.lock
Labels: Feedback: enhancement, dependencies

#203 fix: fix sort button design
  src/index.css
Labels: Feedback: enhancement, Type: design

#204 docs: update docs
  README.en.md
  README.md
  docs/images/screen1.png
  docs/images/screen2.png
  docs/images/tab1.png
  docs/images/tab1dark.png
  docs/images/tab2.png
  docs/images/tab2dark.png
  docs/index.md
Labels: Type: documentation, Feedback: enhancement

#205 refactor: remove unused CSS setting
  src/splash.css
Labels: Feedback: enhancement, Type: design

#206 docs: fix content links
  docs/index.md
Labels: Type: documentation, Feedback: enhancement

#207 perf: change timing of showing the splash window
  src/main.js
Labels: Feedback: enhancement, Type: improvement

#208 style: change style of about.html
  src/about.html
Labels: Feedback: enhancement

#210 feat: change the UI colors to improve readability
  src/index.html
  src/main.css
Labels: Feedback: enhancement, Type: design

#211 docs: add landing page
  docs/_config.yml
  docs/_layouts/default.html
  docs/assets/css/style.scss
  docs/index.md
Labels: Type: documentation, Feedback: enhancement

#212 ci(nodejs.yml): change to run Node CI on pull requests
  .github/workflows/nodejs.yml
Labels: Feedback: enhancement, Type: improvement

#213 docs: modify the file so that lint succeeds
  docs/_layouts/default.html
  docs/assets/css/style.scss
Labels: Feedback: enhancement, Type: improvement

#214 feat: show original developers
  src/lib/parseXML.js
  src/package/package.js
Labels: Feedback: enhancement, Type: new feature

#215 refactor: fix some JSDocs
  src/lib/apmJson.js
  src/lib/mod.js
Labels: Feedback: enhancement, Type: refactoring

#216 feat: add the option to make the version a date
  src/lib/parseXML.js
  src/package/package.js
Labels: Feedback: enhancement, Type: new feature

#217 feat(package.js): support dependency specification by logical OR
  src/package/package.js
Labels: Feedback: enhancement, Type: new feature

#218 Update some packages
  src/main.js
  yarn.lock
Labels: Feedback: enhancement, Type: refactoring, dependencies

#220 Update lint-staged & Specify the version of Node.js
  package.json
  yarn.lock
Labels: Feedback: enhancement, dependencies

#222 docs: update the download link
  README.md
  docs/index.md
Labels: Type: documentation, Feedback: enhancement

#221 feat: estimate the version from the hash
  package.json
  src/core/core.js
  src/lib/getHash.js
  src/lib/parseXML.js
  src/main.js
  src/package/package.js
Labels: Feedback: enhancement, Type: new feature

#223 ci(Dependabot): add a Dependabot setting file
  .github/dependabot.yml
Labels: Feedback: enhancement, Type: improvement

#230 chore: add the Google form to the issue templates
  .github/ISSUE_TEMPLATE/config.yml
Labels: Feedback: enhancement, Type: improvement

#231 docs: add a button link to the release notes
  docs/_layouts/default.html
Labels: Type: documentation, Feedback: enhancement

#232 build(package.json): add 16.x to node engines
  package.json
Labels: Feedback: enhancement, Type: improvement

#233 chore: add a utility to generate SRI
  forge.config.js
  package.json
  util/sri.js
Labels: Feedback: enhancement, Type: improvement

#234 fix: fix a bug that caused interruptions when parsing file elements failed
  src/lib/parseXML.js
Labels: Problem: bug

#240 style: fix html files with prettier
  src/index.html
  src/package_maker.html
Labels: Feedback: enhancement, Type: improvement
