Repository team-apm/apm, pull requests merged in 2021-12, with the labels that each got.

#243 feat: support for data v2 core.xml
  src/core/core.js
  src/lib/parseXML.js
Labels: Feedback: enhancement, Type: new feature

#246 feat: support for data v2 packages.xml and migration
  package.json
  src/core/core.js
  src/index.html
  src/lib/parseXML.js
  src/main.js
  src/migration/migration1to2.js
  src/package/package.js
  src/package/packageUtil.js
  src/preload.js
  src/setting/setting.js
  yarn.lock
Labels: Feedback: enhancement, Type: new feature

#252 refactor: remove btn paramater from many functions
  src/core/core.js
  src/lib/buttonTransition.js
  src/package/package.js
  src/preload.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: refactoring

#253 feat: add a menu to open Google Form
  src/main.js
Labels: Feedback: enhancement, Type: new feature

#254 feat: detect package versions
  src/core/core.js
  src/lib/integrity.js
  src/lib/parseXML.js
  src/package/package.js
Labels: Feedback: enhancement, Type: new feature

#257 docs(README): add contributors in README
  README.en.md
  README.md
Labels: Type: documentation, Feedback: enhancement

#261 feat: update Package Maker
  src/package_maker.html
  src/package_maker_preload.js
Labels: Feedback: enhancement, Type: improvement

#262 fix: fix for dependency resolution
  src/package/package.js
Labels: Problem: bug

#263 fix(package.js): fix for plugin filtering
  src/package/package.js
Labels: Problem: bug

#264 Change to use dot-prop to edit apm.json
  package.json
  src/lib/apmJson.js
  src/migration/migration1to2.js
Labels: Feedback: enhancement, Type: improvement, Type: refactoring

#265 fix: fix for setPackagesList
  src/index.html
  src/package/package.js
Labels: Feedback: enhancement, Type: refactoring

#272 refactor(package.js): add a comment about listJS
  src/package/package.js
Labels: Feedback: enhancement, Type: refactoring

#273 feat: add backups and logs to the migration
  src/main.js
  src/migration/migration1to2.js
Labels: Feedback: enhancement, Type: improvement

#283 perf: prevent too many event handlers
  src/main.js
Labels: Feedback: enhancement, Type: improvement

#282 refactor(UI): improve UI
  src/core/core.js
  src/index.html
  src/package/package.js
  src/package/packageUtil.js
  src/preload.js
  src/setting/setting.js
Labels: Feedback: enhancement, Type: design
