Repository team-apm/apm, pull requests merged in 2022-03, with the labels that each got.

#360 feat(package.js): support for archive integrity
  src/core/core.js
  src/main.js
  src/package/package.js
Labels: Feedback: enhancement, Type: improvement

#352 feat: precise automatic installation of the scripts
  package.json
  src/core/core.js
  src/index.html
  src/lib/parseXML.js
  src/main.js
  src/package/package.js
  src/package_maker_preload.js
  src/preload.js
  yarn.lock
Labels: Feedback: enhancement, Type: improvement, Type: new feature

#398 fix(core.js): support for old mod.xml
  src/core/core.js
Labels: Problem: bug

#400 fix: make an installation directory just before installing
  src/core/core.js
Labels: Problem: bug

#410 docs: update documents
  SECURITY.md
  docs/_config.yml
Labels: Type: documentation, Feedback: enhancement

#413 fix(package.js): fix installation of dependent libraries
  src/package/package.js
Labels: Problem: bug

#415 docs: update documents
  SECURITY.md
  docs/_config.yml
Labels: Type: documentation, Feedback: enhancement

#420 docs: add zip download button in the website
  docs/_config.yml
  docs/_layouts/default.html
Labels: Type: documentation, Feedback: enhancement

#421 fix(shortcut.js): don't create shortcuts in zip version of apm
  src/core/core.js
Labels: Problem: bug

#432 fix(package.js): direct installation of packages without integrity
  src/package/package.js
Labels: Problem: bug

#433 refactor: migrate UI-related files to TypeScript
  CONTRIBUTING.ja.md
  CONTRIBUTING.md
  forge.config.js
  src/about_preload.ts
  src/about_renderer.ts
  src/lib/unzip.js
  src/package/package.js
  src/package_maker_preload.ts
  src/package_maker_renderer.ts
  src/preload.ts
  src/renderer.ts
  src/splash_renderer.ts
Labels: Feedback: enhancement, Type: refactoring
