Repository team-apm/apm, pull requests merged in 2022-06, with the labels that each got.

#597 Refactor imports
  src/lib/apmJson.js
  src/lib/convertId.ts
  src/lib/integrity.js
  src/lib/modList.ts
  src/lib/parseJson.ts
  src/lib/shortcut.js
  src/lib/unzip.js
  src/main.ts
  src/migration/migration1to2.js
  src/migration/migration2to3.ts
  src/migration/parseXML.js
  src/renderer/main/core.js
  src/renderer/main/package.js
  src/renderer/main/packageUtil.js
  src/renderer/main/preload.ts
  src/renderer/main/setting.ts
  src/renderer/package_maker/package_maker_preload.ts
Labels: Feedback: enhancement, Type: refactoring

#599 refactor: make ipcWrapper
  src/lib/convertId.ts
  src/lib/ipcWrapper.ts
  src/lib/modList.ts
  src/main.ts
  src/migration/migration1to2.js
  src/migration/migration2to3.ts
  src/renderer/about/about_preload.ts
  src/renderer/main/core.js
  src/renderer/main/package.js
  src/renderer/main/packageUtil.js
  src/renderer/main/preload.ts
  src/renderer/main/setting.ts
  src/renderer/package_maker/package_maker_preload.ts
Labels: Feedback: enhancement, Type: refactoring

#600 feat(index.html): improve UI added in v3
  src/renderer/main/index.html
Labels: Feedback: enhancement, Type: design, Type: new feature

#601 Refactor Error Handling
  src/lib/apmJson.js
  src/main.ts
  src/migration/migration2to3.ts
  src/renderer/main/core.js
  src/renderer/main/package.js
  src/renderer/main/packageUtil.js
  src/renderer/main/setting.ts
Labels: Feedback: enhancement, Type: refactoring

#602 refactor: make installation and counting verification common
  src/renderer/main/common.ts
  src/renderer/main/core.js
  src/renderer/main/package.js
  src/renderer/main/packageUtil.js
Labels: Feedback: enhancement, Type: refactoring

#588 Refactoring
  src/renderer/main/common.ts
  src/renderer/main/core.js
  src/renderer/main/package.js
  src/renderer/main/packageUtil.js
Labels: Feedback: enhancement, Type: improvement, Type: refactoring

#603 feat: sort packages on startup
  src/lib/updatableList.js
  src/renderer/main/index.html
  src/renderer/main/package.js
  src/renderer/main/packageUtil.js
Labels: Feedback: enhancement, Type: design

#605 fix: change the repository owner of URLs
  CONTRIBUTING.ja.md
  CONTRIBUTING.md
  README.en.md
  README.md
  docs/index.md
  forge.config.js
  package.json
  src/main.ts
  src/migration/migration1to2.js
  src/renderer/main/index.html
Labels: Problem: bug

#604 refactor: reduce the error logs of ENOENT
  src/lib/apmJson.js
Labels: Feedback: enhancement, Type: refactoring

#606 Show an info dialog after migrating v2 to v3
  src/lib/ipcWrapper.ts
  src/main.ts
  src/migration/migration1to2.js
  src/migration/migration2to3.ts
  src/renderer/about/about_preload.ts
  src/renderer/main/packageUtil.js
  src/renderer/main/preload.ts
  src/renderer/main/setting.ts
  src/renderer/package_maker/package_maker_preload.ts
Labels: Feedback: enhancement, Type: improvement, Type: new feature

#607 feat: update data version to v3
  src/lib/apmJson.js
Labels: Feedback: enhancement, Type: new feature

#608 refactor: adjust the way to show a dialog
  src/main.ts
  src/migration/migration2to3.ts
Labels: Feedback: enhancement, Type: improvement, Type: refactoring

#609 docs: update documents for v3.0.0
  SECURITY.md
  docs/_config.yml
Labels: Type: documentation, Feedback: enhancement

#611 refactor: use nullish coalescing operator
  src/lib/buttonTransition.js
  src/lib/unzip.js
  src/renderer/main/package.js
  src/renderer/package_maker/package_maker_preload.ts
Labels: Feedback: enhancement, Type: refactoring

#615 docs: update documents for v3.0.0
  README.en.md
  README.md
  docs/images/tab1.png
  docs/images/tab1dark.png
  docs/images/tab2.png
  docs/images/tab2dark.png
  docs/images/tab3.png
  docs/images/tab3dark.png
  docs/images/tab4.png
  docs/images/tab4dark.png
  docs/images/tab5.png
  docs/images/tab5dark.png
  docs/index.md
Labels: Type: documentation, Feedback: enhancement

#621 fix: change to catch update errors
  src/main.ts
Labels: Problem: bug

#623 feat: improve design
  docs/_layouts/default.html
  docs/assets/css/style.scss
Labels: Type: documentation, Feedback: enhancement, Type: design

#624 feat(index.html): improvement of UI
  src/main.ts
  src/renderer/main.css
  src/renderer/main/index.css
  src/renderer/main/index.html
Labels: Feedback: enhancement, Type: design

#626 docs: update documents for v3.1.0
  docs/_config.yml
Labels: Type: documentation, Feedback: enhancement

#627 fix: catch more update errors
  src/main.ts
Labels: Problem: bug, Feedback: enhancement, Type: refactoring

#651 ci(dependabot): increase the PR limit to 20
  .github/dependabot.yml
Labels: Feedback: enhancement, Type: improvement

#652 docs: update screenshots
  docs/images/tab1.png
  docs/images/tab1dark.png
  docs/images/tab2.png
  docs/images/tab2dark.png
  docs/images/tab3.png
  docs/images/tab3dark.png
  docs/images/tab4.png
  docs/images/tab4dark.png
  docs/images/tab5.png
  docs/images/tab5dark.png
Labels: Type: documentation, Feedback: enhancement

#665 feat: show dependencies
  src/renderer/main/index.html
  src/renderer/main/package.js
Labels: Feedback: enhancement, Type: new feature

#667 fix: avoid migration on new installations
  src/migration/migration1to2.js
  src/migration/migration2to3.ts
Labels: Problem: bug

#666 feat: update UI on main tab
  src/renderer/main/core.js
  src/renderer/main/index.html
Labels: Feedback: enhancement, Type: design

#668 fix(core.js): detect location of exedit.auf
  src/renderer/main/core.js
Labels: Problem: bug

#669 fix: safe remove()
  src/lib/apmPath.ts
  src/lib/modList.ts
  src/lib/safeRemove.ts
  src/renderer/main/common.ts
  src/renderer/main/package.js
  src/renderer/package_maker/package_maker_preload.ts
Labels: Problem: bug

#679 docs(README): make the license section itemization
  README.en.md
  README.md
Labels: Type: documentation, Feedback: enhancement
