Repository team-apm/apm, pull requests merged in 2022-09, with the labels that each got.

#808 fix: fix the problem in installing a script from a website
  src/renderer/main/package.ts
Labels: Problem: bug

#812 Refactor for future removal the warning
  src/migration/migration1to2.ts
  src/renderer/main/package.ts
Labels: Feedback: enhancement, Type: refactoring

#816 docs: update _config.yml
  docs/_config.yml
Labels: Type: documentation, Feedback: enhancement
