Repository team-apm/apm, pull requests merged in 2022-07, with the labels that each got.

#682 fix: Garbled filename when unzipped
  src/lib/unzip.js
Labels: Problem: bug, Feedback: enhancement, Type: refactoring

#694 feat(packageUtil.js): recognize lua files as AviUtl-related files
  src/renderer/main/packageUtil.js
Labels: Feedback: enhancement, Type: improvement

#654 refactor: migrate to TypeScript
  src/lib/apmJson.ts
  src/lib/apmPath.ts
  src/lib/buttonTransition.ts
  src/lib/compareVersion.ts
  src/lib/convertId.ts
  src/lib/getHash.ts
  src/lib/integrity.ts
  src/lib/modList.ts
  src/lib/parseJson.ts
  src/lib/replaceText.ts
  src/lib/shortcut.ts
  src/lib/unzip.ts
  src/lib/updatableList.ts
  src/main.ts
  src/migration/migration1to2.ts
  src/migration/migration2to3.ts
  src/renderer/main/core.ts
  src/renderer/main/package.ts
  src/renderer/main/packageUtil.ts
  src/renderer/main/preload.ts
  src/renderer/main/setting.ts
  src/renderer/package_maker/package_maker_preload.ts
  src/types/apmJson.d.ts
  src/types/node-7z.d.ts
  src/types/packageItem.d.ts
  src/types/win-7zip.d.ts
Labels: Feedback: enhancement, Type: refactoring

#653 refactor: use async await
  src/lib/apmJson.ts
  src/lib/convertId.ts
  src/lib/parseJson.ts
  src/lib/shortcut.ts
  src/migration/migration1to2.ts
  src/migration/migration2to3.ts
  src/renderer/main/core.ts
  src/renderer/main/package.ts
  src/renderer/main/packageUtil.ts
  src/renderer/package_maker/package_maker_preload.ts
Labels: Feedback: enhancement, Type: refactoring

#711 Remove unused feature
  forge.config.js
  package.json
  src/lib/ipcWrapper.ts
  src/main.ts
  src/renderer/main/index.html
  src/renderer/main/preload.ts
  src/renderer/package_maker/package_maker.html
  src/renderer/package_maker/package_maker_preload.ts
  src/renderer/package_maker/package_maker_renderer.ts
  util/sri.js
  yarn.lock
Labels: Feedback: enhancement, Type: improvement, Type: refactoring

#712 refactor: no floating promises
  .eslintrc
  package.json
  src/lib/shortcut.ts
  src/main.ts
  src/migration/migration2to3.ts
  src/renderer/about/about_preload.ts
  src/renderer/main/core.ts
  src/renderer/main/package.ts
  src/renderer/main/packageUtil.ts
  src/renderer/main/preload.ts
  src/renderer/main/setting.ts
  tsconfig.json
  webpack.renderer.config.js
  yarn.lock
Labels: Feedback: enhancement, Type: refactoring

#721 fix: fix batch installation
  src/renderer/main/core.ts
  src/renderer/main/package.ts
  src/renderer/main/setting.ts
Labels: Problem: bug
