Repository team-apm/apm, pull requests merged in 2022-01, with the labels that each got.

#281 feat(convertId): add a feature to convert IDs
  src/core/core.js
  src/lib/convertId.js
  src/lib/parseXML.js
  src/migration/migration1to2.js
  src/preload.js
Labels: Feedback: enhancement, Type: new feature

#288 fix(setting.js): fix for initialization failure
  src/setting/setting.js
Labels: Problem: bug

#289 fix: fix for unexpected download of convert.json
  src/lib/convertId.js
  src/preload.js
Labels: Problem: bug

#308 fix: fix for cache reuse conditions
  src/core/core.js
  src/lib/convertId.js
  src/lib/mod.js
  src/main.js
  src/migration/migration1to2.js
  src/package/packageUtil.js
Labels: Problem: bug

#309 feat: partial supoort for archive integrity
  src/core/core.js
  src/lib/integrity.js
  src/lib/parseXML.js
Labels: Feedback: enhancement, Type: new feature

#311 feat: support releases tag in XML export
  src/lib/parseXML.js
Labels: Feedback: enhancement, Type: improvement

#330 refactor: apm startup process
  src/core/core.js
  src/preload.js
Labels: Feedback: enhancement, Type: refactoring

#331 refactor: add bootstrap icons library
  package.json
  src/index.css
  src/index.html
  src/package_maker.html
  yarn.lock
Labels: Feedback: enhancement, Type: refactoring

#332 fix: prevent package overwriting
  src/core/core.js
  src/package/package.js
  src/package/packageUtil.js
Labels: Problem: bug

#338 feat(packages.js): support for non-archived packages
  src/package/package.js
Labels: Feedback: enhancement, Type: new feature
