Repository team-apm/apm, pull requests merged in 2022-04, with the labels that each got.

#446 ci(Dependabot): raise the dependabot's limit
  .github/dependabot.yml
Labels: Feedback: enhancement, Type: improvement

#459 build(package.json): remove types/twemoji
  package.json
  yarn.lock
Labels: Feedback: enhancement, dependencies

#465 docs(README): add about operation checks and guarantees
  README.en.md
  README.md
Labels: Type: documentation, Feedback: enhancement

#437 refactor: separate files for renderer process
  forge.config.js
  src/about_renderer.ts
  src/lib/parseXML.js
  src/package_maker_renderer.ts
  src/renderer.ts
  src/renderer/about/about.css
  src/renderer/about/about.html
  src/renderer/about/about_preload.ts
  src/renderer/about/about_renderer.ts
  src/renderer/main.css
  src/renderer/main/core.js
  src/renderer/main/index.css
  src/renderer/main/index.html
  src/renderer/main/lib/convertId.js
  src/renderer/main/lib/mod.js
  src/renderer/main/package.js
  src/renderer/main/packageUtil.js
  src/renderer/main/preload.ts
  src/renderer/main/renderer.ts
  src/renderer/main/setting.js
  src/renderer/package_maker/package_maker.html
  src/renderer/package_maker/package_maker_preload.ts
  src/renderer/package_maker/package_maker_renderer.ts
  src/renderer/splash/splash.css
  src/renderer/splash/splash.html
  src/renderer/splash/splash_renderer.ts
  src/splash_renderer.ts
Labels: Feedback: enhancement, Type: refactoring

#470 feat: move apm menu to tabs
  src/main.ts
  src/renderer/main/index.html
  src/renderer/main/preload.ts
Labels: Feedback: enhancement, Type: design

#483 Improve the feature about checking update and auto update
  src/main.ts
  src/renderer/main/index.html
  src/renderer/main/preload.ts
Labels: Feedback: enhancement, Type: improvement, Type: new feature

#419 chore: change repository owner to team-apm
  forge.config.js
  package.json
  src/main.ts
Labels: Feedback: enhancement

#493 fix change repository owner
  forge.config.js
  package.json
  src/main.ts
Labels: Problem: bug, Feedback: enhancement, Type: improvement

#500 fix: fix installing a script
  src/lib/unzip.js
  src/renderer/main/package.js
  webpack.plugins.js
Labels: Problem: bug

#508 fix: change not to make apm.json when changing the installation path
  src/lib/apmJson.js
  src/migration/migration1to2.js
  src/renderer/main/core.js
Labels: Problem: bug, Feedback: enhancement, Type: refactoring
