Repository team-apm/apm, pull requests merged in 2022-05, with the labels that each got.

#489 feat(parseJson): support data v3
  .eslintrc
  package.json
  src/lib/apmJson.js
  src/lib/integrity.js
  src/lib/parseJson.ts
  src/lib/parseXML.js
  src/migration/migration2to3.ts
  src/migration/parseXML.js
  src/renderer/main/core.js
  src/renderer/main/index.html
  src/renderer/main/lib/convertId.ts
  src/renderer/main/lib/mod.js
  src/renderer/main/package.js
  src/renderer/main/packageUtil.js
  src/renderer/main/preload.ts
  src/renderer/main/setting.js
  yarn.lock
Labels: Feedback: enhancement, Type: improvement, Type: refactoring

#532 refactor(mod, settings): Integrate path resolution functionality
  package.json
  src/lib/convertId.ts
  src/lib/modList.ts
  src/lib/parseJson.ts
  src/renderer/main/core.js
  src/renderer/main/lib/mod.js
  src/renderer/main/package.js
  src/renderer/main/preload.ts
  src/renderer/main/setting.ts
  yarn.lock
Labels: Feedback: enhancement, Type: refactoring

#541 docs: update download URL and change the repository owner
  docs/_config.yml
Labels: Type: documentation, Feedback: enhancement

#540 feat: support for split data files
  src/lib/apmPath.ts
  src/lib/convertId.ts
  src/lib/modList.ts
  src/renderer/main/core.js
  src/renderer/main/package.js
  src/renderer/main/setting.ts
  src/renderer/package_maker/package_maker_preload.ts
Labels: Feedback: enhancement, Type: new feature

#553 fix(shortcut.js): specify CWD to the shortcut
  src/lib/shortcut.js
Labels: Problem: bug

#564 fix(package.js): ensure script data is loaded
  src/renderer/main/core.js
  src/renderer/main/package.js
Labels: Problem: bug

#570 fix: fix bugs related to list.json
  src/lib/modList.ts
  src/renderer/main/core.js
  src/renderer/main/package.js
  src/renderer/main/setting.ts
Labels: Problem: bug

#569 feat: add listing the nicommons IDs of the installed packages
  forge.config.js
  src/main.ts
  src/renderer/main/core.js
  src/renderer/main/index.css
  src/renderer/main/index.html
  src/renderer/main/package.js
  src/renderer/main/preload.ts
Labels: Feedback: enhancement, Type: new feature

#586 fix: fix ClipboardJS import
  src/renderer/main/preload.ts
  src/renderer/package_maker/package_maker_preload.ts
Labels: Problem: bug

#587 fix: catch download errors
  src/lib/convertId.ts
  src/main.ts
  src/renderer/main/core.js
  src/renderer/main/package.js
Labels: Problem: bug
