Repository team-apm/apm, pull requests merged in 2023-08, with the labels that each got.

#1090 feat: sharing the video editing environment
  src/lib/ipcWrapper.ts
  src/lib/updatableList.ts
  src/main.ts
  src/renderer/main/common.ts
  src/renderer/main/core.ts
  src/renderer/main/index.css
  src/renderer/main/index.html
  src/renderer/main/package.ts
  src/renderer/main/preload.ts
Labels: Problem: bug, Feedback: enhancement, Type: new feature

#1415 build(deps-dev): bump @electron-forge/* to 6.4.1
  package.json
  yarn.lock
Labels: dependencies

#1224 feat: improve filter functionality
  src/renderer/main/index.css
  src/renderer/main/index.html
  src/renderer/main/package.ts
  src/renderer/main/packageUtil.ts
  src/renderer/main/preload.ts
Labels: Feedback: enhancement, Type: improvement, Type: new feature

#1419 refactor: remove an unnecessary process
  src/renderer/main/package.ts
Labels: Type: refactoring

#1420 build(deps-dev): remove prettier-plugin-md-nocjsp and bump prettier from 2.8.8 to 3.0.2
  .prettierrc
  docs/_layouts/default.html
  package.json
  src/lib/apmJson.ts
  src/lib/apmPath.ts
  src/lib/buttonTransition.ts
  src/lib/compareVersion.ts
  src/lib/convertId.ts
  src/lib/getHash.ts
  src/lib/integrity.ts
  src/lib/ipcWrapper.ts
  src/lib/modList.ts
  src/lib/parseJson.ts
  src/lib/replaceText.ts
  src/lib/safeRemove.ts
  src/lib/shortcut.ts
  src/lib/unzip.ts
  src/lib/updatableList.ts
  src/main.ts
  src/migration/migration1to2.ts
  src/migration/migration2to3.ts
  src/migration/parseXML.js
  src/renderer/about/about.html
  src/renderer/about/about_preload.ts
  src/renderer/main/common.ts
  src/renderer/main/core.ts
  src/renderer/main/index.html
  src/renderer/main/package.ts
  src/renderer/main/packageUtil.ts
  src/renderer/main/preload.ts
  src/renderer/main/setting.ts
  src/renderer/splash/splash.html
  webpack.plugins.ts
  yarn.lock
Labels: dependencies
