Repository team-apm/apm, pull requests merged in 2025-01, with the labels that each got.

#1944 bump electron-log
  package.json
  src/main.ts
  src/renderer/about/about_preload.ts
  src/renderer/main/common.ts
  src/renderer/main/core.ts
  src/renderer/main/package.ts
  src/renderer/main/packageUtil.ts
  src/renderer/main/preload.ts
  src/renderer/main/setting.ts
  yarn.lock
Labels: dependencies, javascript

#1945 docs: add return type annotations to IPC wrapper and common functions
  src/lib/ipcWrapper.ts
  src/renderer/main/common.ts
Labels: Type: documentation

#1946 build(deps-dev): replace npm-run-all with npm-run-all2
  package.json
  yarn.lock
Labels: Type: refactoring

#1947 build(deps): add React and related types to Dependabot configuration
  .github/dependabot.yml
Labels: Type: improvement

#1952 bump css-loader, html-loader, mini-css-extract-plugin, node-loader, and ts-loader
  package.json
  yarn.lock
Labels: dependencies

#1954 build: update Node.js version to 'lts/*' in workflows and package.json
  .github/workflows/build.yml
  .github/workflows/electronegativity.yml
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  package.json
Labels: Type: improvement, dependencies

#1957 make ApmJson class
  src/lib/ApmJson.ts
  src/lib/apmJson.ts
  src/lib/convertId.ts
  src/migration/migration1to2.ts
  src/migration/migration2to3.ts
  src/renderer/main/core.ts
  src/renderer/main/package.ts
  src/renderer/main/packageUtil.ts
Labels: Type: refactoring

#1958 replace Store with Config for improved data management across modules
  src/lib/Config.ts
  src/lib/modList.ts
  src/main/main.ts
  src/migration/migration1to2.ts
  src/migration/migration2to3.ts
  src/renderer/main/core.ts
  src/renderer/main/package.ts
  src/renderer/main/preload.ts
  src/renderer/main/setting.ts
Labels: Type: refactoring

#1959 build(deps-dev): bump electron from 27.3.2 to 33.3.1
  package.json
  yarn.lock
Labels: dependencies, javascript

#1960 chore: correct date retrieval for package check date
  src/renderer/main/package.ts
Labels: Problem: bug

#1961 refactor: fix to use images in React components
  src/renderer/about/About.tsx
  src/renderer/about/index.html
  src/types/image.d.ts
  webpack.renderer.config.ts
Labels: Problem: bug, Type: refactoring

#1971 fix(packageUtil): match() may return null
  src/renderer/main/packageUtil.ts
Labels: Problem: bug
